theme = ["docsy-puzzle", "docsy-plus", "docsy"]

[params]
copyright = "Puzzle ITC GmbH"
imagePrefix = "puzzle_"

enabledModule = "base mobi"

[[Languages.en.menu.main]]
copyright = "Puzzle ITC GmbH"
url = "https://www.puzzle.ch"

[params.replaceContent]
allowedHrefHosts = ['localhost', 'puzzle.ch', 'acend.ch']

[[params.replaceContent.placeholders]]
placeholder = "<docker-registry>"
queryParam = "r"
defaultValue = "<docker-registry>"

[[params.replaceContent.placeholders]]
placeholder = "<proxy>:<port>"
queryParam = "p"
defaultValue = "<proxy>:<port>"

############################## social links ##############################
[params.links]
[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/acend/container-basics-training"

[[params.links.user]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/puzzleitc"

[[params.links.user]]
name = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://linkedin.com/company/puzzle-itc/"
