name: Trigger Gitlab Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: call webhook
      run: |
        curl -X POST \
          -F token=${{ secrets.GITLAB_TOKEN }} \
          -F "ref=master" \
          -F "variables[GITHUB_SHA]=$GITHUB_SHA" \
          -F "variables[GITHUB_REF]=$GITHUB_REF" \
          https://gitlab.puzzle.ch/api/v4/projects/1863/trigger/pipeline
