name: PRCleanup
on:
  pull_request:
    types: [closed]

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Remove PR Environment'
        uses: 'deliverybot/helm@v1'
        with:
          # Task remove means to remove the helm release.
          task: 'remove'
          release: 'pr-${{ github.event.pull_request.number }}'
          namespace: 'acend-container-basics-training-test'
          version: '${{ github.sha }}'
          repository: 'https://acend.github.io/helm-charts/'
          chart: 'acend-training-chart'
          token: '${{ github.token }}'
          helm: 'helm3'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_TEST }}'
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1.1.1
      with:
        args: '-X DELETE -H "Authorization: Bearer ${{ secrets.FIXME }}" https://quay.io/api/v1/repository/${{ github.repository }}/tag/pr-${{ github.event.pull_request.number }}'
